server:
  port: 8000
spring:
  application:
    name: bin-gateway
  # 引入 Nacos 动态配置
  config:
    import:
      - optional:nacos:bin-gateway.yml
      - optional:nacos:bin-gateway-routes.yml
  # Nacos 服务发现 + 配置中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.220.128:8848
        namespace: ${NACOS_NAMESPACE:bin-cloud}
        group: Gateway
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:Beyond129814.}
      config:
        server-addr: 192.168.220.128:8848
        namespace: ${NACOS_NAMESPACE:bin-cloud}
        group: Gateway
        file-extension: yml
        refresh-enabled: true
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:Beyond129814.}