CREATE TABLE sys_application (
    id BIGINT PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    icon_url VARCHAR(500) NOT NULL DEFAULT '',
    entry_url VARCHAR(500) NOT NULL,
    service_id VARCHAR(100) NOT NULL,
    client_secret_hash CHAR(64) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    sso_enabled TINYINT(1) NOT NULL DEFAULT 1,
    sort INT NOT NULL DEFAULT 10,
    version INT NOT NULL DEFAULT 0,
    is_delete TINYINT NOT NULL DEFAULT 0,
    active_code VARCHAR(64) GENERATED ALWAYS AS (CASE WHEN is_delete=0 THEN code ELSE NULL END) STORED,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modify DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_user VARCHAR(64) NOT NULL DEFAULT 'system',
    modify_user VARCHAR(64) NOT NULL DEFAULT 'system',
    UNIQUE KEY uk_application_code (active_code),
    UNIQUE KEY uk_application_service (service_id),
    KEY idx_application_status (status, sort, is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_application_redirect_uri (
    id BIGINT PRIMARY KEY,
    application_id BIGINT NOT NULL,
    environment VARCHAR(16) NOT NULL DEFAULT 'DEV',
    redirect_uri VARCHAR(500) NOT NULL,
    logout_uri VARCHAR(500) NOT NULL DEFAULT '',
    available TINYINT(1) NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 0,
    is_delete TINYINT NOT NULL DEFAULT 0,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modify DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_user VARCHAR(64) NOT NULL DEFAULT 'system',
    modify_user VARCHAR(64) NOT NULL DEFAULT 'system',
    UNIQUE KEY uk_application_redirect (application_id, redirect_uri),
    FOREIGN KEY (application_id) REFERENCES sys_application(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_tenant_application (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    access_policy VARCHAR(16) NOT NULL DEFAULT 'ASSIGNED',
    entry_url_override VARCHAR(500) NOT NULL DEFAULT '',
    opened_at DATETIME NULL,
    effective_at DATETIME NULL,
    expire_at DATETIME NULL,
    suspended_at DATETIME NULL,
    closed_at DATETIME NULL,
    config_json JSON NULL,
    comment VARCHAR(500) NOT NULL DEFAULT '',
    version INT NOT NULL DEFAULT 0,
    is_delete TINYINT NOT NULL DEFAULT 0,
    active_application_id BIGINT GENERATED ALWAYS AS (CASE WHEN is_delete=0 THEN application_id ELSE NULL END) STORED,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modify DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_user VARCHAR(64) NOT NULL DEFAULT 'system',
    modify_user VARCHAR(64) NOT NULL DEFAULT 'system',
    UNIQUE KEY uk_tenant_application_active (tenant_id, active_application_id),
    UNIQUE KEY uk_tenant_application_tenant (tenant_id, id),
    UNIQUE KEY uk_tenant_application_boundary (tenant_id, application_id, id),
    KEY idx_tenant_application_status (tenant_id, status, expire_at, is_delete),
    FOREIGN KEY (tenant_id) REFERENCES sys_tenant(id),
    FOREIGN KEY (application_id) REFERENCES sys_application(id),
    CHECK (expire_at IS NULL OR effective_at IS NULL OR expire_at > effective_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_user_application (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    tenant_application_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    effective_at DATETIME NULL,
    expire_at DATETIME NULL,
    granted_by BIGINT NULL,
    granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    comment VARCHAR(500) NOT NULL DEFAULT '',
    version INT NOT NULL DEFAULT 0,
    is_delete TINYINT NOT NULL DEFAULT 0,
    active_user_id BIGINT GENERATED ALWAYS AS (CASE WHEN is_delete=0 THEN user_id ELSE NULL END) STORED,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modify DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_user VARCHAR(64) NOT NULL DEFAULT 'system',
    modify_user VARCHAR(64) NOT NULL DEFAULT 'system',
    UNIQUE KEY uk_user_application_active (tenant_application_id, active_user_id),
    KEY idx_user_application_user (tenant_id, user_id, status, expire_at),
    FOREIGN KEY (tenant_id, user_id) REFERENCES sys_user(tenant_id, id),
    FOREIGN KEY (tenant_id, tenant_application_id) REFERENCES sys_tenant_application(tenant_id, id),
    CHECK (expire_at IS NULL OR effective_at IS NULL OR expire_at > effective_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_sso_session (
    id BIGINT PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    parent_session_id VARCHAR(64) NULL,
    tenant_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL,
    tenant_application_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    credential_version INT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    refresh_token_hash CHAR(64) NULL,
    auth_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_access_at DATETIME NULL,
    expire_at DATETIME NOT NULL,
    revoked_at DATETIME NULL,
    revoke_reason VARCHAR(200) NOT NULL DEFAULT '',
    client_ip VARCHAR(45) NOT NULL DEFAULT '',
    user_agent VARCHAR(500) NOT NULL DEFAULT '',
    version INT NOT NULL DEFAULT 0,
    is_delete TINYINT NOT NULL DEFAULT 0,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modify DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_user VARCHAR(64) NOT NULL DEFAULT 'system',
    modify_user VARCHAR(64) NOT NULL DEFAULT 'system',
    UNIQUE KEY uk_sso_session (session_id),
    UNIQUE KEY uk_sso_refresh (refresh_token_hash),
    KEY idx_sso_instance_user (tenant_application_id, user_id, status, expire_at),
    KEY idx_sso_parent (parent_session_id, status),
    KEY idx_sso_tenant_user (tenant_id, user_id, status),
    FOREIGN KEY (tenant_id, user_id) REFERENCES sys_user(tenant_id, id),
    FOREIGN KEY (tenant_id, application_id, tenant_application_id) REFERENCES sys_tenant_application(tenant_id, application_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sys_sso_login_log (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NULL,
    application_id BIGINT NULL,
    tenant_application_id BIGINT NULL,
    user_id BIGINT NULL,
    event_type VARCHAR(32) NOT NULL,
    success TINYINT(1) NOT NULL DEFAULT 1,
    failure_code VARCHAR(64) NOT NULL DEFAULT '',
    session_id VARCHAR(64) NOT NULL DEFAULT '',
    trace_id VARCHAR(64) NOT NULL DEFAULT '',
    client_ip VARCHAR(45) NOT NULL DEFAULT '',
    user_agent VARCHAR(500) NOT NULL DEFAULT '',
    event_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_sso_log_tenant_time (tenant_id, event_time),
    KEY idx_sso_log_app_time (application_id, event_time),
    KEY idx_sso_log_session (session_id),
    KEY idx_sso_log_result (success, event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO sys_application (id, code, name, description, entry_url, service_id, sso_enabled)
VALUES (1, 'platform-console', '平台管理端', '统一身份与应用管理', '/dashboard', 'admin-api', 0),
       (2, 'learning-workbench', '学习工作台', '实际运行的应用隔离与单点登录示例', '/api/open/workbench/start', 'open-api', 1);
INSERT INTO sys_application_redirect_uri (id, application_id, redirect_uri)
VALUES (1, 2, 'http://localhost:5173/api/open/workbench/callback');
